In [8]:

import datetime as dt
import pandas as pd
import numpy as np
import random as rd
import random
from datetime import date

In [9]:
dt = date(2019, 1, 1) # set the date and time (time defaults to 00)
dt.strftime('%D %I:%M') # set the date and time to a string

'01/01/19 12:00'

In [10]:
# initial date is 01 Jan 2019, so we need to generate a number of dates past this
start_date = date.today().replace(day=1, month=1).toordinal()
end_date = date.today().toordinal()

In [11]:
# in order to create a random array of dates
# taken from this website and ammended: https://stackoverflow.com/questions/50165501/generate-random-list-of-timestamps-in-python


import time
random_day1 = [] #dates = []
random_day2 = [] #dates = []
random_day3 = [] #dates = []
def randomDate(start, end):
    frmt = '%d-%m-%Y' #%H:%M:%S'
    stime = time.mktime(time.strptime(start, frmt))
    etime = time.mktime(time.strptime(end, frmt))
    ptime = stime + random.random() * (etime - stime)
    dt = date.fromtimestamp(time.mktime(time.localtime(ptime)))
    return dt

In [12]:
for i in range(0 , 100):
    random_day1.append(randomDate("01-01-2019", "01-04-2019"))
    random_day2.append(randomDate("01-04-2019", "01-08-2019"))
    random_day3.append(randomDate("01-08-2019", "15-12-2019"))
    
array_random_day1_dataframe = pd.DataFrame(random_day1, columns=['Creation Date'])
array_random_day2_dataframe = pd.DataFrame(random_day2, columns=['InProgress Date'])
array_random_day3_dataframe = pd.DataFrame(random_day3, columns=['Closed Date'])
pd.concat([array_random_day1_dataframe, array_random_day2_dataframe, array_random_day3_dataframe], axis=1)

   Creation Date InProgress Date Closed Date
0     2019-02-15      2019-07-19  2019-09-27
1     2019-02-21      2019-07-07  2019-08-26
2     2019-02-21      2019-07-10  2019-09-28
3     2019-01-22      2019-05-06  2019-09-22
4     2019-03-13      2019-05-14  2019-12-04
5     2019-02-07      2019-06-07  2019-08-03
6     2019-03-26      2019-07-28  2019-10-21
7     2019-03-07      2019-05-29  2019-11-21
8     2019-02-17      2019-06-26  2019-11-03
9     2019-03-01      2019-05-24  2019-12-11
10    2019-03-12      2019-07-30  2019-08-13
11    2019-01-26      2019-07-03  2019-08-19
12    2019-03-28      2019-07-14  2019-11-28
13    2019-01-08      2019-04-30  2019-11-29
14    2019-03-20      2019-05-18  2019-12-09
15    2019-02-04      2019-07-30  2019-12-07
16    2019-03-05      2019-04-30  2019-09-27
17    2019-01-30      2019-06-06  2019-11-18
18    2019-02-10      2019-07-20  2019-11-19
19    2019-02-17      2019-04-01  2019-09-28
20    2019-02-11      2019-07-15  2019-12-13
21    2019-01-22      2019-06-10  2019-08-21
22    2019-02-19      2019-04-03  2019-10-12
23    2019-02-18      2019-07-24  2019-08-08
24    2019-02-17      2019-04-11  2019-12-01
25    2019-03-06      2019-04-08  2019-11-25
26    2019-02-04      2019-07-18  2019-11-02
27    2019-03-29      2019-06-24  2019-12-13
28    2019-03-04      2019-05-12  2019-09-22
29    2019-02-20      2019-05-13  2019-10-09
..           ...             ...         ...
70    2019-01-29      2019-04-12  2019-11-01
71    2019-02-26      2019-05-25  2019-10-14
72    2019-02-21      2019-06-08  2019-09-06
73    2019-02-13      2019-06-21  2019-08-03
74    2019-01-29      2019-05-18  2019-11-12
75    2019-01-23      2019-07-01  2019-10-01
76    2019-02-16      2019-04-22  2019-11-07
77    2019-01-14      2019-04-21  2019-08-30
78    2019-01-04      2019-04-05  2019-12-06
79    2019-03-28      2019-07-01  2019-09-08
80    2019-02-18      2019-04-12  2019-11-15
81    2019-02-15      2019-07-02  2019-09-14
82    2019-03-04      2019-05-09  2019-12-01
83    2019-02-19      2019-07-12  2019-09-07
84    2019-01-04      2019-04-24  2019-10-03
85    2019-01-16      2019-06-29  2019-12-05
86    2019-01-12      2019-04-14  2019-08-04
87    2019-03-10      2019-04-17  2019-08-07
88    2019-02-11      2019-04-10  2019-09-05
89    2019-01-09      2019-07-10  2019-11-10
90    2019-01-29      2019-06-02  2019-10-06
91    2019-03-04      2019-07-18  2019-09-15
92    2019-01-16      2019-04-25  2019-10-18
93    2019-03-12      2019-07-19  2019-11-11
94    2019-03-23      2019-06-22  2019-12-06
95    2019-01-06      2019-06-08  2019-10-01
96    2019-01-17      2019-06-19  2019-10-01
97    2019-02-14      2019-04-26  2019-09-01
98    2019-02-06      2019-07-07  2019-09-12
99    2019-01-13      2019-04-01  2019-11-01

[100 rows x 3 columns]

In [13]:
len(random_day1)

100

In [15]:
#random_day2 = date.fromordinal(random.randint(start_date, end_date))
#random_day2

In [16]:
#random_day3 = date.fromordinal(random.randint(start_date, end_date))
#random_day3

In [17]:
# I need to chnage between list and date time types to be able to perform some calculation on the actual dates.

newdate1 = time.strptime(random_day1, "%d/%m/%Y") 
newdate2 = time.strptime(random_day2, "%d/%m/%Y") 

if newdate1 > newdate2:
    print('day 1 is older than day 2')
elif newdate1 < newdate2:
    print('day 2 is older than day 1')


#Let's say you have the initial dates as strings like these:
#date1 = "31/12/2015"
#date2 = "01/01/2016"

#You can do the following:
#newdate1 = time.strptime(date1, "%d/%m/%Y") and newdate2 = time.strptime(date2, "%d/%m/%Y") to convert them to python's date format. Then, the comparison is obvious:

#newdate1 > newdate2 will return False
#newdate1 < newdate2 will return True

TypeError: strptime() argument 0 must be str, not <class 'list'>

In [ ]:
# simple code to decipher the largest date 
# i.e. the closing date of the case. 

if random_day1 > random_day2:
        if random_day1 > random_day3:
            case_closed_date = random_day1
        else: 
            case_closed_date = random_day3
elif random_day2 > random_day3:
        if random_day2 > random_day1:
            case_closed_date = random_day2
        else: 
            case_closed_date = random_day1
elif random_day3 > random_day1:
        if random_day3 > random_day2:
            case_closed_date = random_day3
        else:
            case_closed_date = random_day2

case_closed_date

In [ ]:
# simple code to decipher the smallest date 
# i.e. the opening date of the case. 

if random_day1 < random_day2:
    if random_day1 < random_day3:
        case_opened_date = random_day1
    else: 
        case_opened_date = random_day3
elif random_day2 < random_day3:
    if random_day2 < random_day1:
        case_opened_date = random_day2
    else: 
        case_opened_date = random_day1
elif random_day3 < random_day1:
    if random_day3 < random_day2:
        case_opened_date = random_day3
    else:
        case_opened_date = random_day2

case_opened_date

In [ ]:
# lets try a different approach to my logic FFS!
if (case_opened_date or case_closed_date) == (random_day1 or random_day2):
    case_middle_date = random_day3
elif (case_opened_date or case_closed_date) == (random_day2 or random_day3):
    case_middle_date = random_day1
elif (case_opened_date or case_closed_date) == (random_day3 or random_day1):
      case_middle_date = random_day2

case_middle_date

In [ ]:
# OK so we have created the 3 dates for one case, now we need to put them in a 
# dataframe and we need to increase the number of rows.

#array_random_day1 = np.arange(start=array_random_day1[0], stop=array_random_day1[100], step=1)
#array_random_day1_dataframe = pd.DataFrame(array_random_day1, columns=['Date Opened'])
#array_random_day1_dataframe

array_random_dates_dataframe = pd.DataFrame(data=np.array([['',case_opened_date, case_middle_date, case_closed_date]])) #, columns=['Expert', 'Rand1', 'rand3']]))
df = array_random_dates_dataframe
df

In [ ]:
# We need to run the creation of the dates 100 times, 
# and we also need to run the functions of finding the 
# earliest, latest and middle dates and place them in 
# an array so we can work them into 
# a dataframe so we can then start plotting etc.


for i in range(0 , 100):
    #dates.append(randomDate("01-01-2019", "15-12-2019"))
    
    
    # initial date is 01 Jan 2019, so we need to generate a number of dates past this
    start_date = date.today().replace(day=1, month=1).toordinal()
    end_date = date.today().toordinal()
    random_day1 = date.fromordinal(random.randint(start_date, end_date))
    random_day2 = date.fromordinal(random.randint(start_date, end_date))
    random_day3 = date.fromordinal(random.randint(start_date, end_date))
    
# simple code to decipher the largest date 
# i.e. the closing date of the case. 

    if random_day1 > random_day2:
        if random_day1 > random_day3:
            case_closed_date = random_day1
        else: 
            case_closed_date = random_day3
    elif random_day2 > random_day3:
        if random_day2 > random_day1:
            case_closed_date = random_day2
        else: 
            case_closed_date = random_day1
    elif random_day3 > random_day1:
        if random_day3 > random_day2:
            case_closed_date = random_day3
        else:
            case_closed_date = random_day2   

    # simple code to decipher the smallest date 
# i.e. the opening date of the case. 

    if random_day1 < random_day2:
        if random_day1 < random_day3:
            case_opened_date = random_day1
        else: 
            case_opened_date = random_day3
    elif random_day2 < random_day3:
        if random_day2 < random_day1:
            case_opened_date = random_day2
        else: 
            case_opened_date = random_day1
    elif random_day3 < random_day1:
        if random_day3 < random_day2:
            case_opened_date = random_day3
        else:
            case_opened_date = random_day2

#case_opened_date 
    
    
 # code to decipher the middle date between initial date (case open) and final date (case closed)
    if (case_opened_date or case_closed_date) == (random_day1 or random_day2):
        case_middle_date = random_day3
    elif (case_opened_date or case_closed_date) == (random_day2 or random_day3):
        case_middle_date = random_day1
    elif (case_opened_date or case_closed_date) == (random_day3 or random_day1):
         case_middle_date = random_day2   
    
    
#array_dates_dataframe = pd.DataFrame(dates, columns=['Case Creation Date'])

df = array_dates_dataframe
df

In [ ]:
# Using a simple few lines of code to covnnvert the date to an integer. The reason this is required
# is so that we can use these integer values to generate a number between this and the last date
# available in the range and then convert it back to a date again
# that will be between the initial date, this one and the final one 
# where the case is closed.


# Taken and ammended from here: https://stackoverflow.com/questions/28154066/how-to-convert-datetime-to-integer-in-python 
# on 14th December 2019

import datetime

#def to_integer(dt(random_day):
def to_integer(dt_time):    
   return 10000*dt_time.year + 100*dt_time.month + dt_time.day
    # Or take the appropriate chars from a string date representation.


to_integer(random_day) # returns the random integer for the random day
x = to_integer(random_day)
x

In [ ]:
# We just generated the initial date's integer, so we now need to create 
# a random number between this and the last number in the range.
# last number in the range has to be todays date, so.....

y = to_integer(date.today()) # uses to integer function to change todays date to an integer

z = random.randrange(x, y, 1) # create a random integer between the 1st random date (int), the last date (today) witha  step of 1

z

In [ ]:
# Now we need to create a 3rd date between the initial 2 dates we created
#for the simple reason that we need to the case opened date, closed date 
# and the date it was worked on

t = random.randrange(x, z, 1)
t

In [ ]:
dt.strftime('date.today')
date.today()

In [ ]:
dt.today()